//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsUygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not
    {
        public int Id { get; set; }
        public Nullable<double> Vize1 { get; set; }
        public Nullable<double> Vize2 { get; set; }
        public Nullable<double> Final { get; set; }
        public Nullable<bool> GeçtiMiKaldiMi { get; set; }
        public Nullable<int> OgrId { get; set; }
        public Nullable<int> DersId { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
